In [88]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import to_categorical

# Load the training data
train_data = pd.read_csv("train.csv", usecols=range(1,20531))
X = train_data.copy()
y = pd.read_csv("train_labels.csv", usecols=range(1,2))

In [89]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical


label_map = {'BRCA': 0, 'COAD': 1, 'KIRC': 2, 'LUAD': 3, 'PRAD': 4}

# Map the string class labels to integer values
y = y.replace(label_map)
# Convert class labels to one-hot encoded binary vectors
y = to_categorical(y)

# Scale the input features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Define the model architecture
model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.3))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dense(5, activation='softmax'))

# Compile the model with categorical_crossentropy loss function
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=20, verbose=2)

# Load the test data
test_data = pd.read_csv("test.csv")

Epoch 1/20
18/18 - 2s - loss: 0.2542 - accuracy: 0.9143 - val_loss: 0.1098 - val_accuracy: 0.9786 - 2s/epoch - 134ms/step
Epoch 2/20
18/18 - 1s - loss: 0.0943 - accuracy: 0.9893 - val_loss: 0.1492 - val_accuracy: 0.9929 - 1s/epoch - 68ms/step
Epoch 3/20
18/18 - 1s - loss: 0.3817 - accuracy: 0.9804 - val_loss: 0.0495 - val_accuracy: 0.9929 - 1s/epoch - 71ms/step
Epoch 4/20
18/18 - 1s - loss: 0.2318 - accuracy: 0.9857 - val_loss: 2.8086e-06 - val_accuracy: 1.0000 - 1s/epoch - 69ms/step
Epoch 5/20
18/18 - 1s - loss: 0.2185 - accuracy: 0.9893 - val_loss: 0.0092 - val_accuracy: 0.9929 - 1s/epoch - 69ms/step
Epoch 6/20
18/18 - 1s - loss: 0.0663 - accuracy: 0.9964 - val_loss: 0.0000e+00 - val_accuracy: 1.0000 - 1s/epoch - 69ms/step
Epoch 7/20
18/18 - 1s - loss: 0.0992 - accuracy: 0.9929 - val_loss: 0.0000e+00 - val_accuracy: 1.0000 - 1s/epoch - 78ms/step
Epoch 8/20
18/18 - 2s - loss: 0.0028 - accuracy: 0.9982 - val_loss: 0.0000e+00 - val_accuracy: 1.0000 - 2s/epoch - 114ms/step
Epoch 9/20
18/18 - 1s - loss: 0.1001 - accuracy: 0.9982 - val_loss: 1.1069e-08 - val_accuracy: 1.0000 - 1s/epoch - 71ms/step
Epoch 10/20
18/18 - 1s - loss: 0.1127 - accuracy: 0.9929 - val_loss: 0.0460 - val_accuracy: 0.9929 - 1s/epoch - 71ms/step
Epoch 11/20
18/18 - 1s - loss: 0.2263 - accuracy: 0.9964 - val_loss: 0.0000e+00 - val_accuracy: 1.0000 - 1s/epoch - 70ms/step
Epoch 12/20
18/18 - 1s - loss: 0.6926 - accuracy: 0.9875 - val_loss: 1.7030e-09 - val_accuracy: 1.0000 - 1s/epoch - 71ms/step
Epoch 13/20
18/18 - 1s - loss: 0.1549 - accuracy: 0.9946 - val_loss: 5.7655e-06 - val_accuracy: 1.0000 - 1s/epoch - 71ms/step
Epoch 14/20
18/18 - 1s - loss: 0.4590 - accuracy: 0.9982 - val_loss: 0.0000e+00 - val_accuracy: 1.0000 - 1s/epoch - 71ms/step
Epoch 15/20
18/18 - 1s - loss: 0.1134 - accuracy: 0.9946 - val_loss: 0.0000e+00 - val_accuracy: 1.0000 - 1s/epoch - 70ms/step
Epoch 16/20
18/18 - 1s - loss: 0.0575 - accuracy: 0.9982 - val_loss: 0.0000e+00 - val_accuracy: 1.0000 - 1s/epoch - 72ms/step
Epoch 17/20
18/18 - 2s - loss: 0.2131 - accuracy: 0.9929 - val_loss: 6.9319e-05 - val_accuracy: 1.0000 - 2s/epoch - 109ms/step
Epoch 18/20
18/18 - 2s - loss: 4.5342e-08 - accuracy: 1.0000 - val_loss: 0.0050 - val_accuracy: 0.9929 - 2s/epoch - 84ms/step
Epoch 19/20
18/18 - 1s - loss: 0.0888 - accuracy: 0.9964 - val_loss: 3.9169e-08 - val_accuracy: 1.0000 - 1s/epoch - 69ms/step
Epoch 20/20
18/18 - 1s - loss: 0.0468 - accuracy: 0.9964 - val_loss: 0.0000e+00 - val_accuracy: 1.0000 - 1s/epoch - 69ms/step

In [90]:
train_data.head()

,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,...,gene_20520,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529
0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,0.0,...,7.205236,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759
1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,0.0,...,10.639259,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168
2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,0.0,...,10.336027,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023
3,0.0,3.467853,3.581918,6.620243,9.706829,0.0,7.758510,0.000000,0.0,0.0,...,7.831035,5.726657,8.602588,9.928339,6.096154,9.816001,11.556995,9.244150,9.836473,5.355133
4,0.0,1.224966,1.691177,6.572007,9.640511,0.0,6.754888,0.531868,0.0,0.0,...,6.830293,5.105904,7.927968,9.673966,1.877744,9.802692,13.256060,9.664486,9.244219,8.330912

In [91]:
test_data.head()

,Unnamed: 0,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
0,sample_661,0.000000,3.395872,3.274023,7.050251,9.895044,0.0,6.898390,0.969307,0.0,...,6.645844,9.276713,10.125284,4.298526,10.140664,10.269407,10.548485,9.958225,8.306577,0.000000
1,sample_72,1.482332,2.907198,4.034365,6.613129,9.456295,0.0,10.038850,0.000000,0.0,...,5.147535,7.685660,10.155552,6.664853,8.469345,12.737940,10.332171,8.624295,8.378936,0.000000
2,sample_9,0.000000,3.642494,4.423558,6.849511,9.464466,0.0,7.947216,0.724214,0.0,...,6.020051,8.712809,10.259096,6.131583,9.923582,11.144295,9.244851,9.484299,4.759151,0.000000
3,sample_316,0.000000,4.365686,4.142609,6.310825,8.623929,0.0,8.268182,1.436801,0.0,...,7.016452,8.868810,10.720501,1.995521,10.332137,11.305788,11.012834,9.786600,4.141212,0.512783
4,sample_519,0.000000,3.981588,4.008218,6.870698,9.477366,0.0,6.972830,0.545771,0.0,...,6.524266,9.411676,10.069087,6.364375,10.120640,11.287528,10.915386,9.641678,5.012032,0.000000

In [92]:
# Load the test data
test_data = pd.read_csv("test.csv", usecols=range(1,20531))

# Scale the test data
test_data_scaled = scaler.transform(test_data)

y_pred_proba = model.predict(test_data_scaled)

# Get the predicted classes
y_pred = np.argmax(y_pred_proba, axis=1)

4/4 [==============================] - 0s 12ms/step

In [93]:
first_col = pd.read_csv("test.csv", usecols=range(0,1))

In [94]:
y_pred= pd.DataFrame(y_pred,columns=['Class'])

In [95]:
label_map = {0: 'BRCA', 1:'COAD', 2:'KIRC', 3: 'LUAD', 4:'PRAD'}

preds_col = y_pred.replace(label_map)

In [96]:
res= pd.concat([first_col, preds_col], axis=1)

In [97]:
res

     Unnamed: 0 Class
0    sample_661  PRAD
1     sample_72  BRCA
2      sample_9  PRAD
3    sample_316  KIRC
4    sample_519  PRAD
..          ...   ...
96   sample_531  COAD
97   sample_148  LUAD
98   sample_151  LUAD
99   sample_521  KIRC
100  sample_559  KIRC

[101 rows x 2 columns]

In [98]:
res.to_csv('answer.csv', index=False, encoding = 'utf-8-sig')

from google.colab import files
files.download('answer.csv')